export const ROLES = ['ADMIN', 'LIBRARIAN', 'ASSISTANT_LIBRARIAN', 'FACULTY', 'STUDENT']
export const STAFF_ROLES = ['ADMIN', 'LIBRARIAN', 'ASSISTANT_LIBRARIAN']
export const INSTITUTION_NAME = 'Vignan Institute of Information Technology'
export const BOOK_COPY_STATUSES = ['AVAILABLE', 'ISSUED', 'RESERVED', 'DAMAGED', 'LOST', 'UNDER_REPAIR']
export const CIRCULATION_STATUSES = ['ISSUED', 'RETURNED', 'OVERDUE', 'LOST', 'DAMAGED']
export const RESERVATION_STATUSES = ['PENDING', 'READY_FOR_PICKUP', 'FULFILLED', 'COMPLETED', 'REJECTED', 'CANCELLED', 'EXPIRED']
export const FINE_STATUSES = ['PENDING', 'PARTIALLY_PAID', 'PAID', 'WAIVED']
